[build]
  base = "outoftheblue_site_v4_12_rules_fix"
  publish = "outoftheblue_site_v4_12_rules_fix"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
